### ISSUE TITLE
About the oe-set

### ISSUE THREAD

**Issue by HopeFinder** [zjysteven/MixOE#1]
Hello! According Sec. 3.1 in your paper, you have refered to "your ood datasets in both fine-grained and coarse-grained are from FGVC". But I find that a new dataset(WebVision) is used in your code during training of MixOE. As I understand, WebVision is an auxiliary outlier set which is used by other methods(i.e., OE). Could you tell me why it is also used by MixOE? What are the real datasets used by MixOE as the OOD training sets?

**Comment by zjysteven** [comment]
Hi, MixOE does use an auxiliary outlier set (or equivalently, OOD training set), which is the WebVision in this work. For a fair comparison, we also let other OE-based methods use this outlier set during training. The difference between MixOE and other methods is how they leverage the training outliers.

Sec. 3.1 describes the test environment, so all the data we mention there is used for the test, and we make sure that no model will see those test OOD data (either coarse-grained or fine-grained) by removing all bird/aircraft/butterfly/car images from the outlier set WebVision (see Sec. 5.1 "The auxiliary outlier set").

Hope that these answer your questions. Let me know if you have lingering ones.

**Comment by HopeFinder** [comment]
Thank you for timely reply! I understand it, thanks a lot.

**Comment by zjysteven** [comment]
Great. I'm closing this issue then, but feel free to ask other questions.
