### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by HopeFinder** [zjysteven/MixOE#2]
Hello, I run the "train.sh" and find that there is no pre-trained weight in your code but it should be used (FileNotFoundError: [Errno 2] No such file or directory: '../checkpoints/car/split_2/rn_baseline_epochs=90_bs=32/seed_0.pth').
Could you tell me where I can get the pre-trained weight? Thanks a lot!

**Comment by zjysteven** [comment]
That checkpoint is the trained weight of the corresponding baseline model (with standard cross-entropy loss), which you can obtain by running [train_baseline.py](https://github.com/zjysteven/MixOE/tree/main/train/train_baseline.py) (also see [sample script](https://github.com/zjysteven/MixOE/blob/main/scripts/train.sh) for instructions).

For convenience, I've uploaded the pre-trained baseline weights to [here](https://drive.google.com/drive/folders/1XdGWCgYR1lBiJZIuhlO0e3VHisJ8MDlH?usp=sharing). Let me know if there are any issues.

**Comment by HopeFinder** [comment]
> That checkpoint is the trained weight of the corresponding baseline model (with standard cross-entropy loss), which you can obtain by running [train_baseline.py](https://github.com/zjysteven/MixOE/tree/main/train/train_baseline.py) (also see [sample script](https://github.com/zjysteven/MixOE/blob/main/scripts/train.sh) for instructions).
> 
> For convenience, I've uploaded the pre-trained baseline weights to [here](https://drive.google.com/drive/folders/1XdGWCgYR1lBiJZIuhlO0e3VHisJ8MDlH?usp=sharing). Let me know if there are any issues.

Thank you for your reply! I have solved this problem according to your advice.

**Comment by zjysteven** [comment]
Glad to know!
