### ISSUE TITLE
Update for arxiv

### ISSUE THREAD

**Issue by RuoyuChen10** [zjysteven/MixOE#3]
Hi there, thanks for your excellent work. The current version of arxiv is 2021, can you offer a latest version of your paper? Thanks.

**Comment by zjysteven** [comment]
Hi, sorry for the late response. I've updated the arxiv, and it should be available within a few days. Thanks for your interest in our paper!

**Comment by RuoyuChen10** [comment]
> Hi, sorry for the late response. I've updated the arxiv, and it should be available within a few days. Thanks for your interest in our paper!

Thanks, looking forward to seeing the latest work.

**Comment by zjysteven** [comment]
In addition to the arxiv version, the official WACV version has also been released here https://openaccess.thecvf.com/content/WACV2023/html/Zhang_Mixture_Outlier_Exposure_Towards_Out-of-Distribution_Detection_in_Fine-Grained_Environments_WACV_2023_paper.html
